version: '3.7'

services:

  db:
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - ./volumes/postgresql/pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./
    container_name: sound_cloud_web
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/src/app
      - ./static:/src/static
      - ./media:/src/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: sound_cloud_nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - web

volumes:
  audio_library_postgres_data: null
