version: '3.7'

services:
  web:
    build: ./
    container_name: sound_cloud_web
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/src/app
      - ./static:/src/app/static
      - ./media:/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12
    volumes:
      - audio_library_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    container_name: sound_cloud_nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - web

# volumes:
#   audio_library_postgres_data: