# Generated by Django 2.2.24 on 2021-10-23 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cociallink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_related', to='accounts.AuthUser'),
        ),
    ]
